// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7ZexT2J08c6F8WSVioeAhv49CQUjDsMA',
    appId: '1:883288807598:web:957a15f03e2da2ede3f53f',
    messagingSenderId: '883288807598',
    projectId: 'com-techwiz-plantpal',
    authDomain: 'com-techwiz-plantpal.firebaseapp.com',
    storageBucket: 'com-techwiz-plantpal.appspot.com',
    measurementId: 'G-NBDFN2PXSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO0l-m5b53Akw1tneWbBwahmTQYvQPnbo',
    appId: '1:883288807598:android:5282e42a3927e9ffe3f53f',
    messagingSenderId: '883288807598',
    projectId: 'com-techwiz-plantpal',
    storageBucket: 'com-techwiz-plantpal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSzolKhdmKZTwx_VBuxpClAoLl2Gt1Y_Q',
    appId: '1:883288807598:ios:e8c8bc1be6c44f6ee3f53f',
    messagingSenderId: '883288807598',
    projectId: 'com-techwiz-plantpal',
    storageBucket: 'com-techwiz-plantpal.appspot.com',
    iosClientId: '883288807598-hr9a09fpath5a0efdlekck3m2vtlidbs.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantpal',
  );
}
