// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXslrL32pEX3w42K3n17elKBGCUBUEey0',
    appId: '1:252047642311:web:083091382f14aa43b7f8e2',
    messagingSenderId: '252047642311',
    projectId: 'com-techwiz4-plantpal-cb3a9',
    authDomain: 'com-techwiz4-plantpal-cb3a9.firebaseapp.com',
    storageBucket: 'com-techwiz4-plantpal-cb3a9.appspot.com',
    measurementId: 'G-B0B8S04X0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmwWTMKcEW0Uxo8mIMt1zrVHcEdxHuCvA',
    appId: '1:252047642311:android:6b55dfe0da5b93f3b7f8e2',
    messagingSenderId: '252047642311',
    projectId: 'com-techwiz4-plantpal-cb3a9',
    storageBucket: 'com-techwiz4-plantpal-cb3a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAopzo2uuNMMD_mJ4Av4iMK_nuw3GC5_nM',
    appId: '1:252047642311:ios:47e488614bf2c3d9b7f8e2',
    messagingSenderId: '252047642311',
    projectId: 'com-techwiz4-plantpal-cb3a9',
    storageBucket: 'com-techwiz4-plantpal-cb3a9.appspot.com',
    iosClientId: '252047642311-8af4ltrs9km86cq8mbnd0jpc3pca73s5.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantpal',
  );
}
