// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcMrGxFUjRcaP4qF4oMy4nq-CvTUK3g34',
    appId: '1:1078568301244:web:2f61e71b24313bf72b56b9',
    messagingSenderId: '1078568301244',
    projectId: 'com-techwiz4-plantpal',
    authDomain: 'com-techwiz4-plantpal.firebaseapp.com',
    storageBucket: 'com-techwiz4-plantpal.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-FoxHCmZvUf2N7TrLVOoppldB89Zb3as',
    appId: '1:1078568301244:android:35df5242c593b1632b56b9',
    messagingSenderId: '1078568301244',
    projectId: 'com-techwiz4-plantpal',
    storageBucket: 'com-techwiz4-plantpal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD7y-jxWDH25DJJ7TJomLQ_Cm-Lfb0bYQ',
    appId: '1:1078568301244:ios:8968ece29d9280062b56b9',
    messagingSenderId: '1078568301244',
    projectId: 'com-techwiz4-plantpal',
    storageBucket: 'com-techwiz4-plantpal.appspot.com',
    iosClientId: '1078568301244-6ecqnolui7kqn599af9e41mgsv7jjufg.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantpal',
  );
}
